apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kong-system

bases:
  - ../../base/kong
  - ../../base/keycloak

commonLabels:
  environment: dev

patchesStrategicMerge:
  - patches/kong-replicas.yaml
  - patches/keycloak-replicas.yaml
