apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
  namespace: keycloak
data:
  KC_DB: "postgres"
  KC_HOSTNAME: "auth.jobzy.fi"
  KC_PROXY: "edge"
  KC_HEALTH_ENABLED: "true"
  KC_METRICS_ENABLED: "true"
  KC_HTTP_ENABLED: "true"
  KC_HOSTNAME_STRICT: "false"
  KEYCLOAK_LOGLEVEL: "INFO"
  ROOT_LOGLEVEL: "INFO"
