apiVersion: v1
kind: Secret
metadata:
  name: keycloak-postgres-secret
  namespace: keycloak
type: Opaque
stringData:
  username: "keycloak"
  password: "REPLACE_WITH_ACTUAL_PASSWORD"
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin-secret
  namespace: keycloak
type: Opaque
stringData:
  username: "admin"
  password: "REPLACE_WITH_ADMIN_PASSWORD"
